from pathlib import Path
p=Path('index.html')
s=p.read_text(encoding='utf-8')
if 'id="medalCeremony"' in s:
    print('Ceremony already present; no change.')
    raise SystemExit(0)

css=r'''
/* MEDAL CEREMONY */
.previewCeremonyBtn{border:0;padding:12px 16px;border-radius:14px;background:linear-gradient(#8e72fa,#6749d1);color:#fff;font-weight:900;font-size:15px;box-shadow:0 6px 0 #4e34a4;user-select:none}.previewCeremonyBtn:active{transform:translateY(3px);box-shadow:0 3px 0 #4e34a4}
#fiestaCover .fc-preview{display:block;margin:3px auto 8px;border:0;border-radius:999px;padding:7px 15px;background:#5e43b9;color:#fff;font-weight:900;font-size:12px;box-shadow:0 4px 0 #3f2b83}#fiestaCover .fc-preview:active{transform:translateY(2px);box-shadow:0 2px 0 #3f2b83}
#medalCeremony{position:fixed;inset:0;z-index:200000;display:none;align-items:center;justify-content:center;padding:14px;background:radial-gradient(circle at 50% 25%,#fff7bc 0,#85cef8 43%,#185b9d 100%);overflow:hidden;font-family:"Trebuchet MS","Arial Rounded MT Bold",Arial,sans-serif}#medalCeremony.show{display:flex;animation:mcFade .35s ease-out}
.mc-card{position:relative;width:min(920px,96vw);height:min(650px,94vh);min-height:540px;border:5px solid #fff1a0;border-radius:32px;background:linear-gradient(#dff5ff 0 58%,#86d167 58% 70%,#c78b5b 70% 100%);box-shadow:0 25px 65px #071e3c66;overflow:hidden;text-align:center}.mc-card:before{content:"";position:absolute;inset:0;background:radial-gradient(circle at 15% 13%,#fff9 0 2px,transparent 3px),radial-gradient(circle at 82% 21%,#fff8 0 3px,transparent 4px);background-size:86px 82px,117px 101px;pointer-events:none}
.mc-banner{position:relative;z-index:4;margin:18px auto 0;width:min(720px,88%);padding:10px 14px;border-radius:17px;background:linear-gradient(#fff7ab,#efb726);border:4px solid #fff;color:#7b4b00;font-size:clamp(22px,4vw,40px);font-weight:1000;text-shadow:0 2px #fff;box-shadow:0 6px 0 #a86d0b}.mc-sub{position:relative;z-index:4;margin:9px auto 0;color:#16527f;font-weight:900;font-size:clamp(14px,2vw,20px)}
.mc-stage{position:absolute;left:0;right:0;bottom:35px;height:430px}.mc-side{position:absolute;bottom:12px;width:145px;height:82px;border:4px solid #dce8f2;border-radius:16px 16px 5px 5px;background:linear-gradient(#ecf2f7,#afc3d2);box-shadow:0 7px 0 #6e8596;font-weight:1000;color:#557184;padding-top:12px}.mc-side.left{right:calc(50% + 153px)}.mc-side.right{left:calc(50% + 153px)}
.mc-podium{position:absolute;left:50%;bottom:12px;transform:translateX(-50%) translateY(145px);width:290px;height:135px;border:5px solid #fff0a0;border-radius:20px 20px 7px 7px;background:linear-gradient(#ffe36c,#e9a91b);box-shadow:0 10px 0 #9d650d;animation:mcPodium .65s .15s cubic-bezier(.2,.9,.3,1.1) forwards}.mc-podium:before{content:"1";font-size:82px;line-height:1.35;font-weight:1000;color:#fff;text-shadow:0 5px #bf7d0d}
.mc-player{position:absolute;left:50%;bottom:118px;transform:translateX(-50%);z-index:3;width:225px;height:300px;object-fit:contain;filter:drop-shadow(0 12px 10px #29435755);animation:mcPlayer .75s cubic-bezier(.2,.9,.3,1.15)}
.mc-medal{position:absolute;left:50%;top:100px;z-index:6;width:100px;height:130px;transform:translate(-50%,-210px) scale(.55);opacity:0}.mc-medal:before,.mc-medal:after{content:"";position:absolute;top:0;width:36px;height:68px;border-radius:7px 7px 13px 13px}.mc-medal:before{left:17px;background:linear-gradient(#65b2ff,#1d6fc9);transform:rotate(10deg)}.mc-medal:after{right:17px;background:linear-gradient(#ff7b7b,#d63737);transform:rotate(-10deg)}.mc-face{position:absolute;z-index:2;left:50%;bottom:0;transform:translateX(-50%);width:94px;height:94px;border-radius:50%;display:grid;place-items:center;background:radial-gradient(circle at 32% 28%,#fff9cc,#ffd84c 49%,#e29b13);border:6px solid #fff1a6;box-shadow:0 0 0 4px #b87509,0 8px 16px #71450055;color:#fff;font-size:48px;text-shadow:0 3px #af6c00}.mc-card.award .mc-medal{animation:mcMedal 1.1s cubic-bezier(.2,.9,.3,1.08) forwards}.mc-glow{position:absolute;left:50%;top:210px;width:380px;height:380px;border-radius:50%;transform:translate(-50%,-50%) scale(.3);background:radial-gradient(circle,#fff37abb,#ffde2c33 48%,transparent 70%);opacity:0}.mc-card.celebrate .mc-glow{animation:mcGlow 1s ease-out forwards}
.mc-message{position:absolute;z-index:7;left:50%;bottom:1px;transform:translateX(-50%);width:92%;font-size:clamp(17px,2.4vw,26px);font-weight:1000;color:#fff;text-shadow:0 3px #185183}.mc-close{position:absolute;right:13px;top:13px;z-index:10;width:44px;height:44px;border-radius:50%;border:3px solid #fff;background:#e94d4d;color:#fff;font-size:22px;font-weight:1000;box-shadow:0 4px #a72a2a}.mc-previewTag{display:none;position:absolute;left:13px;top:13px;z-index:10;padding:6px 10px;border-radius:999px;background:#6347bd;color:#fff;font-size:12px;font-weight:1000}.mc-card.preview .mc-previewTag{display:block}
.mc-piece{position:absolute;z-index:200010;top:-25px;width:10px;height:18px;border-radius:2px;pointer-events:none;animation:mcFall var(--dur) linear var(--delay) forwards}.mini-piece{position:fixed;z-index:199990;width:9px;height:15px;border-radius:2px;pointer-events:none;animation:miniPop .85s ease-out forwards}
@keyframes mcFade{from{opacity:0}to{opacity:1}}@keyframes mcPodium{to{transform:translateX(-50%) translateY(0)}}@keyframes mcPlayer{from{transform:translateX(-50%) translateY(90px) scale(.82);opacity:0}to{transform:translateX(-50%) translateY(0) scale(1);opacity:1}}@keyframes mcMedal{0%{transform:translate(-50%,-210px) scale(.55);opacity:0}25%{opacity:1}72%{transform:translate(-50%,112px) scale(1.08)}88%{transform:translate(-50%,98px) scale(.97)}100%{transform:translate(-50%,104px) scale(1);opacity:1}}@keyframes mcGlow{0%{opacity:0;transform:translate(-50%,-50%) scale(.3)}60%{opacity:1;transform:translate(-50%,-50%) scale(1.15)}100%{opacity:.78;transform:translate(-50%,-50%) scale(1)}}@keyframes mcFall{to{transform:translateY(110vh) translateX(var(--drift)) rotate(var(--rot));opacity:.9}}@keyframes miniPop{to{transform:translate(var(--x),var(--y)) rotate(var(--r));opacity:0}}
@media(max-width:620px){.mc-card{height:92vh;min-height:510px}.mc-stage{height:380px;bottom:25px}.mc-player{width:185px;height:250px;bottom:110px}.mc-podium{width:235px;height:118px}.mc-side{display:none}.mc-medal{top:94px}}
'''
s=s.replace('</style>',css+'\n</style>',1)

html=r'''<section id="medalCeremony" aria-hidden="true"><div class="mc-card"><button class="mc-close" type="button" onclick="closeMedalCeremony()">×</button><div class="mc-previewTag">TEACHER PREVIEW</div><div class="mc-banner">🏆 GOLD MEDAL CEREMONY 🏆</div><div class="mc-sub" id="mcSub">All 11 Sports Fiesta challenges completed perfectly!</div><div class="mc-stage"><div class="mc-glow"></div><div class="mc-side left">2nd</div><div class="mc-side right">3rd</div><div class="mc-podium"></div><img class="mc-player" id="mcPlayer" alt="Player 1 receiving the gold medal"><div class="mc-medal"><div class="mc-face">★</div></div><div class="mc-message" id="mcMessage">Player 1, step onto the champion's rostrum!</div></div></div></section>'''
marker='<!-- SPORTS_FIESTA_COVER_END -->'
s=s.replace(marker,marker+html,1)

cover_btn='<button class="fc-start" id="fcStart">★ START SPORTS FIESTA ★</button>'
s=s.replace(cover_btn,cover_btn+'<button class="fc-preview" type="button" onclick="unlockCeremonyPreview()">🔒 Preview Gold Medal Ceremony</button>',1)
reset_btn='<button id="resetBtn" class="resetBtn" type="button">Hold 5 Seconds to Reset</button>'
s=s.replace(reset_btn,'<button class="previewCeremonyBtn" type="button" onclick="unlockCeremonyPreview()">🔒 Preview Medal Ceremony</button> '+reset_btn,1)
s=s.replace('localStorage.removeItem(STORAGE_KEY);','localStorage.removeItem(STORAGE_KEY);\n    localStorage.removeItem(CEREMONY_SHOWN_KEY);',1)

old='''  if(goldUnlocked){\n    goldNote.className = "goldNote goldUnlocked";\n    goldNote.textContent = "🏆 Gold Medal Unlocked! You completed all 11 practices perfectly in single-player mode!";\n  }else{\n    goldNote.className = "goldNote";\n    goldNote.textContent = "Not unlocked yet — keep going! 🌟";\n  }\n}'''
new='''  if(goldUnlocked){\n    goldNote.className = "goldNote goldUnlocked";\n    goldNote.textContent = "🏆 Gold Medal Unlocked! You completed all 11 practices perfectly in single-player mode!";\n    if(localStorage.getItem(CEREMONY_SHOWN_KEY)!=="1") setTimeout(maybeAutoGoldCeremony,450);\n  }else{\n    goldNote.className = "goldNote";\n    goldNote.textContent = "Not unlocked yet — keep going! 🌟";\n    localStorage.removeItem(CEREMONY_SHOWN_KEY);\n  }\n}'''
if old not in s: raise SystemExit('gold block not found')
s=s.replace(old,new,1)

s=s.replace('saveProgress(data);\n  renderAll();\n}\n\nfunction togglePerfect','saveProgress(data);\n  if(state.completed) miniCelebrate(false);\n  renderAll();\n}\n\nfunction togglePerfect',1)
s=s.replace('saveProgress(data);\n  renderAll();\n}\n\nfunction reportFromGame','saveProgress(data);\n  if(state.perfectSingle) miniCelebrate(true);\n  renderAll();\n}\n\nfunction reportFromGame',1)
s=s.replace('saveProgress(data);\n  renderAll();\n}\n\n// Optional auto-report','saveProgress(data);\n  if(state.perfectSingle || state.completed) miniCelebrate(!!state.perfectSingle);\n  renderAll();\n}\n\n// Optional auto-report',1)

js=r'''
const CEREMONY_SHOWN_KEY="sportsFiestaGoldCeremonyShown_v1";let ceremonyAudioCtx=null,ceremonyTimers=[];
function ca(){if(!ceremonyAudioCtx){const C=window.AudioContext||window.webkitAudioContext;if(C)ceremonyAudioCtx=new C()}if(ceremonyAudioCtx&&ceremonyAudioCtx.state==="suspended")ceremonyAudioCtx.resume();return ceremonyAudioCtx}
function ct(f,d=.12,t="triangle",v=.04,delay=0){const c=ca();if(!c)return;const x=c.currentTime+delay,o=c.createOscillator(),g=c.createGain();o.type=t;o.frequency.setValueAtTime(f,x);g.gain.setValueAtTime(.0001,x);g.gain.exponentialRampToValueAtTime(v,x+.01);g.gain.exponentialRampToValueAtTime(.0001,x+d);o.connect(g).connect(c.destination);o.start(x);o.stop(x+d+.03)}
function drum(){for(let i=0;i<10;i++)ct(i%2?150:118,.07,"square",.025,i*.075)}function ding(){ct(880,.12,"sine",.05);ct(1320,.28,"sine",.035,.09)}function fanfare(){[523,659,784,1047].forEach((f,i)=>ct(f,.28,"triangle",.045,i*.11));[659,784,1047,1319].forEach((f,i)=>ct(f,.35,"sine",.03,.48+i*.08))}
function confetti(n=100){const h=document.getElementById("medalCeremony"),c=["#ffd43b","#ff5964","#49cfff","#5bdd70","#9d67ff","#ff934d","#fff"];if(!h)return;for(let i=0;i<n;i++){const e=document.createElement("i");e.className="mc-piece";e.style.left=Math.random()*100+"vw";e.style.background=c[i%c.length];e.style.setProperty("--dur",2.4+Math.random()*2+"s");e.style.setProperty("--delay",Math.random()*.4+"s");e.style.setProperty("--drift",-110+Math.random()*220+"px");e.style.setProperty("--rot",Math.random()*900-450+"deg");h.appendChild(e);setTimeout(()=>e.remove(),4800)}}
function miniCelebrate(perfect=false){ct(perfect?740:620,.09,"triangle",.03);ct(perfect?1040:820,.14,"triangle",.03,.08);const c=["#ffd43b","#ff5964","#49cfff","#5bdd70","#9d67ff"],n=perfect?32:18;for(let i=0;i<n;i++){const e=document.createElement("i"),a=Math.PI*2*i/n,d=65+Math.random()*(perfect?180:110);e.className="mini-piece";e.style.left="50vw";e.style.top="45vh";e.style.background=c[i%c.length];e.style.setProperty("--x",Math.cos(a)*d+"px");e.style.setProperty("--y",Math.sin(a)*d+"px");e.style.setProperty("--r",Math.random()*700-350+"deg");document.body.appendChild(e);setTimeout(()=>e.remove(),950)}}
function clearCT(){ceremonyTimers.forEach(clearTimeout);ceremonyTimers=[]}
function p1src(){const a=document.getElementById("fcP1");if(a&&a.src)return a.src;const b=document.querySelector(".playerCard img");return b?b.src:""}
function showMedalCeremony(preview=false){const e=document.getElementById("medalCeremony"),c=e&&e.querySelector(".mc-card");if(!e||!c)return;clearCT();e.querySelectorAll(".mc-piece").forEach(x=>x.remove());c.classList.remove("award","celebrate","preview");if(preview)c.classList.add("preview");document.getElementById("mcPlayer").src=p1src();document.getElementById("mcSub").textContent=preview?"Password accepted — preview only. Saved progress is unchanged.":"All 11 Sports Fiesta challenges completed perfectly!";document.getElementById("mcMessage").textContent="Player 1, step onto the champion's rostrum!";e.classList.add("show");e.setAttribute("aria-hidden","false");if(!preview)localStorage.setItem(CEREMONY_SHOWN_KEY,"1");drum();ceremonyTimers.push(setTimeout(()=>{c.classList.add("award");document.getElementById("mcMessage").textContent="Presenting the Sports Fiesta Gold Medal…";ding()},900));ceremonyTimers.push(setTimeout(()=>{c.classList.add("celebrate");document.getElementById("mcMessage").textContent="🏆 GOLD MEDAL CHAMPION — WELL DONE, PLAYER 1! 🏆";fanfare();confetti(115)},1900))}
function closeMedalCeremony(){clearCT();const e=document.getElementById("medalCeremony");if(!e)return;e.classList.remove("show");e.setAttribute("aria-hidden","true");e.querySelectorAll(".mc-piece").forEach(x=>x.remove())}
function maybeAutoGoldCeremony(){if(localStorage.getItem(CEREMONY_SHOWN_KEY)==="1")return;if(document.body.classList.contains("cover-on")){ceremonyTimers.push(setTimeout(maybeAutoGoldCeremony,600));return}showMedalCeremony(false)}
function unlockCeremonyPreview(){const p=window.prompt("Enter password to preview the gold medal ceremony:");if(p===null)return;if(p.trim()==="67")showMedalCeremony(true);else{ct(180,.15,"sawtooth",.025);window.alert("Incorrect password.")}}
document.addEventListener("keydown",e=>{if(e.key==="Escape")closeMedalCeremony()});
'''
anchor='\nrenderAll();\n</script>'
if anchor not in s: raise SystemExit('script anchor not found')
s=s.replace(anchor,'\n'+js+anchor,1)
p.write_text(s,encoding='utf-8')
print('Medal ceremony installed.')
